#Code generated by: Microsoft Copilot

import pygame
import time

#Description: Visualizes an image full screen for t number of seconds
def visualizer(path, t):
    pygame.init()

    # Fullscreen window
    screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
    sw, sh = screen.get_size()

    # Load + scale image
    img = pygame.image.load(path)
    img = pygame.transform.scale(img, (sw, sh))
    
    screen.blit(img, (0, 0))
    pygame.display.flip()

    time.sleep(t)
    pygame.quit()


# Tester Call
#visualizer("random.jpg",2)